version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: shawl-db
    restart: always
    ports:
      - 3001:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/shawl-mysql
      - ./config:/etc/shawl-mysql
      - ./mysql-files:/var/lib/shwl-mysql-files
